export const ADDGAME = "ADDGAME";
export const SETCURRENTGAME = "SETCURRENTGAME";
export const SETDATE = "SETDATE";
export const ADDPLAYER = "ADDPLAYER";
export const ADDFAVOURITE = "ADDFAVOURITE";
export const UPDATEGAMES = "UPDATEGAMES";
export const SETWINNERS = "SETWINNERS";
export const UPDATEFAVOURITE = "UPDATEFAVOURITE";
export const SETHOTTEST = "SETHOTTEST";
export const RESETPLAYERS = "RESETPLAYERS";
export const UPDATESCORE = "UPDATESCORE";
export const UPDATEVISIBILITY = "UPDATEVISIBILITY";


